name: Build Android APK Release

# 触发条件：仅在创建tag时自动编译
on:
  push:
    tags: [ 'v*' ]
  workflow_dispatch: # 允许手动触发

jobs:
  # Android构建任务
  build-android:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        
    - name: Cache Gradle packages
      uses: actions/cache@v4
      with:
        path: |
          ~/.gradle/caches
          ~/.gradle/wrapper
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
        restore-keys: |
          ${{ runner.os }}-gradle-
          
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
      
    # 构建Android Release APK（未签名）
    - name: Build Android Release APK
      run: ./gradlew :composeApp:assembleRelease
      
    # 签名APK
    - name: Sign app APK
      uses: r0adkll/sign-android-release@v1
      id: sign_app
      with:
        releaseDirectory: composeApp/build/outputs/apk/release
        signingKeyBase64: ${{ secrets.ANDROID_KEYSTORE_BASE64 }}
        alias: ${{ secrets.ANDROID_KEY_ALIAS }}
        keyStorePassword: ${{ secrets.ANDROID_KEYSTORE_PASSWORD }}
        keyPassword: ${{ secrets.ANDROID_KEY_PASSWORD }}
      env:
        # 设置build-tools版本
        BUILD_TOOLS_VERSION: "35.0.0"
      
    # 重命名已签名的APK文件
    - name: Rename signed APK
      run: |
        # 获取tag名称
        TAG_NAME=${GITHUB_REF#refs/tags/}
        if [ -z "$TAG_NAME" ] || [ "$TAG_NAME" = "$GITHUB_REF" ]; then
          TAG_NAME="latest"
        fi
        
        # 重命名签名后的APK文件
        mv ${{steps.sign_app.outputs.signedReleaseFile}} bProject_${TAG_NAME}_android.apk
        
        echo "APK文件重命名成功: bProject_${TAG_NAME}_android.apk"
        ls -la *.apk
      
    - name: Upload Android Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: android-release-apk
        path: |
          *.apk
        retention-days: 30

  # 创建Release（编译完成后自动发布）
  create-release:
    needs: [build-android]
    runs-on: ubuntu-latest
    
    steps:
    - name: Download Android Artifacts
      uses: actions/download-artifact@v4
      with:
        name: android-release-apk
        path: ./artifacts/android/
        
    # 验证下载的APK文件
    - name: Verify Downloaded APK
      run: |
        echo "下载的APK文件:"
        ls -la ./artifacts/android/
        
        # 检查APK文件是否存在
        if [ ! -f ./artifacts/android/*.apk ]; then
          echo "错误: 未找到APK文件"
          exit 1
        fi
        
    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        files: |
          ./artifacts/android/*.apk
        draft: false
        prerelease: false
        tag_name: ${{ github.ref_name }}
        name: bProject ${{ github.ref_name }} - Android Release
        body: |
          ### Android APK 安装说明
          1. **Android**: 下载 `bProject_${{ github.ref_name }}_android.apk` 文件
             - 在Android设备上启用"未知来源"安装权限
             - 直接安装APK文件即可
             - 支持Android API 24+ (Android 7.0+)
          
          ### 应用信息
          - **包名**: ovo.sypw.bsp
          - **版本**: ${{ github.ref_name }}
          - **最低Android版本**: Android 7.0 (API 24)
          - **目标Android版本**: 根据项目配置
          
          ### 更新内容
          - 最新的功能更新和bug修复
          - 性能优化和稳定性提升
          - Android平台特定优化
          
          ### 注意事项
          - 首次安装可能需要授予相关权限
          - 建议在安装前卸载旧版本以避免冲突
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}