name: Build All Platforms Release

# 触发条件：仅在创建tag时自动编译
on:
  push:
    tags: [ '*v*' ]
  workflow_dispatch: # 允许手动触发

jobs:
  # Android构建任务
  build-android:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        
    - name: Cache Gradle packages
      uses: actions/cache@v4
      with:
        path: |
          ~/.gradle/caches
          ~/.gradle/wrapper
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
        restore-keys: |
          ${{ runner.os }}-gradle-
          
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
      
    # 构建Android Release APK（未签名）
    - name: Build Android Release APK
      run: ./gradlew :composeApp:assembleRelease
      env:
        MY_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      
    # 签名APK
    - name: Sign app APK
      uses: r0adkll/sign-android-release@v1
      id: sign_app
      with:
        releaseDirectory: composeApp/build/outputs/apk/release
        signingKeyBase64: ${{ secrets.ANDROID_KEYSTORE_BASE64 }}
        alias: ${{ secrets.ANDROID_KEY_ALIAS }}
        keyStorePassword: ${{ secrets.ANDROID_KEYSTORE_PASSWORD }}
        keyPassword: ${{ secrets.ANDROID_KEY_PASSWORD }}
      env:
        # 设置build-tools版本
        BUILD_TOOLS_VERSION: "35.0.0"
      
    # 重命名已签名的APK文件
    - name: Rename signed APK
      run: |
        # 获取tag名称
        TAG_NAME=${GITHUB_REF#refs/tags/}
        if [ -z "$TAG_NAME" ] || [ "$TAG_NAME" = "$GITHUB_REF" ]; then
          TAG_NAME="latest"
        fi
        
        # 重命名签名后的APK文件
        mv ${{steps.sign_app.outputs.signedReleaseFile}} bProject_${TAG_NAME}_android.apk
        
        echo "APK文件重命名成功: bProject_${TAG_NAME}_android.apk"
        ls -la *.apk
      
    - name: Upload Android Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: android-release-apk
        path: |
          *.apk
        retention-days: 30

  # Windows构建任务（包含MSI安装包和可执行文件）
  build-windows:
    runs-on: windows-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        
    - name: Cache Gradle packages
      uses: actions/cache@v4
      with:
        path: |
          ~/.gradle/caches
          ~/.gradle/wrapper
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
        restore-keys: |
          ${{ runner.os }}-gradle-
          
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
      shell: bash
      
    # 构建Windows可执行文件
    - name: Build Windows Executable
      run: ./gradlew :composeApp:createDistributable
      shell: bash
      env:
        MY_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      
    # 构建Windows MSI安装包
    - name: Build Windows MSI
      run: ./gradlew :composeApp:packageMsi
      shell: bash
      env:
        MY_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      
    # 分别上传Windows MSI和可执行文件
    - name: Upload Windows MSI
      uses: actions/upload-artifact@v4
      with:
        name: windows-msi
        path: |
          composeApp/build/compose/binaries/main/msi/*.msi
        retention-days: 30
        
    - name: Upload Windows Executable
      uses: actions/upload-artifact@v4
      with:
        name: windows-executable
        path: |
          composeApp/build/compose/binaries/main/app/
        retention-days: 30

  # macOS构建任务
  build-macos:
    runs-on: macos-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        
    - name: Cache Gradle packages
      uses: actions/cache@v4
      with:
        path: |
          ~/.gradle/caches
          ~/.gradle/wrapper
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
        restore-keys: |
          ${{ runner.os }}-gradle-
          
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
      
    # 构建macOS DMG安装包
    - name: Build macOS DMG
      run: ./gradlew :composeApp:packageDmg
      env:
        MY_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Upload macOS Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: macos-desktop-app
        path: |
          composeApp/build/compose/binaries/main/dmg/*.dmg
          composeApp/build/compose/binaries/main/app/
        retention-days: 30
      env:
        MY_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  # Linux构建任务
  build-linux:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        
    - name: Cache Gradle packages
      uses: actions/cache@v4
      with:
        path: |
          ~/.gradle/caches
          ~/.gradle/wrapper
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
        restore-keys: |
          ${{ runner.os }}-gradle-
          
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
      
    # 构建Linux DEB安装包
    - name: Build Linux DEB
      run: ./gradlew :composeApp:packageDeb
      env:
        MY_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Upload Linux Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: linux-desktop-app
        path: |
          composeApp/build/compose/binaries/main/deb/*.deb
          composeApp/build/compose/binaries/main/app/
        retention-days: 30
      env:
        MY_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  # 创建Release（所有平台编译完成后自动发布）
  create-release:
    needs: [build-android, build-windows, build-macos, build-linux]
    runs-on: ubuntu-latest
    
    steps:
    - name: Download Android Artifacts
      uses: actions/download-artifact@v4
      with:
        name: android-release-apk
        path: ./artifacts/android/
        
    - name: Download Windows MSI
      uses: actions/download-artifact@v4
      with:
        name: windows-msi
        path: ./artifacts/windows/msi/
        
    - name: Download Windows Executable
      uses: actions/download-artifact@v4
      with:
        name: windows-executable
        path: ./artifacts/windows/app/
        
    - name: Download macOS Artifacts
      uses: actions/download-artifact@v4
      with:
        name: macos-desktop-app
        path: ./artifacts/macos/
        
    - name: Download Linux Artifacts
      uses: actions/download-artifact@v4
      with:
        name: linux-desktop-app
        path: ./artifacts/linux/
        
    # 验证下载的文件
    - name: Verify Downloaded Files
      run: |
        echo "下载的Android APK文件:"
        ls -la ./artifacts/android/
        
        echo "下载的Windows文件:"
        ls -la ./artifacts/windows/
        
        echo "下载的macOS文件:"
        ls -la ./artifacts/macos/
        
        echo "下载的Linux文件:"
        ls -la ./artifacts/linux/
        
        # 检查APK文件是否存在
        if [ ! -f ./artifacts/android/*.apk ]; then
          echo "错误: 未找到APK文件"
          exit 1
        fi
        
    # 重命名文件为规范格式
    - name: Rename Release Files
      run: |
        # 获取tag名称
        TAG_NAME=${GITHUB_REF#refs/tags/}
        
        # 处理Windows文件
        # 重命名MSI文件
        cd ./artifacts/windows/msi/
        if [ -f *.msi ]; then
          mv *.msi "../../../bProject_${TAG_NAME}_windows.msi"
        fi
        cd ../../../
        
        # 打包Windows可执行文件
        cd ./artifacts/windows/app/
        zip -r "../../../bProject_${TAG_NAME}_windows.zip" .
        cd ../../../
        
        # 重命名macOS文件
        cd ./artifacts/macos/
        if [ -f *.dmg ]; then
          mv *.dmg "bProject_${TAG_NAME}_macos.dmg"
        fi
        cd ../..
        
        # 重命名Linux文件
        cd ./artifacts/linux/
        if [ -f *.deb ]; then
          mv *.deb "bProject_${TAG_NAME}_linux.deb"
        fi
        cd ../..
        
        # 验证重命名后的文件
        echo "重命名后的文件列表:"
        find ./artifacts -name "bProject_${TAG_NAME}_*" -type f
        ls -la ./bProject_${TAG_NAME}_windows.zip 2>/dev/null || echo "Windows zip文件未找到"
        
    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        files: |
          ./artifacts/android/*.apk
          ./bProject_${{ github.ref_name }}_windows.msi
          ./bProject_${{ github.ref_name }}_windows.zip
          ./artifacts/macos/bProject_${{ github.ref_name }}_macos.dmg
          ./artifacts/linux/bProject_${{ github.ref_name }}_linux.deb
        draft: false
        prerelease: false
        tag_name: ${{ github.ref_name }}
        name: bProject ${{ github.ref_name }}
        body: |
          使用Github Actions自动构建发布
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}